# Generated by Django 5.0.4 on 2024-04-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
