# Generated by Django 5.0.4 on 2024-04-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
