# Generated by Django 5.0.4 on 2024-04-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_address_first_name_address_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pstatus',
            field=models.CharField(default='', max_length=20),
        ),
    ]
