# Generated by Django 5.0.4 on 2024-04-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
