# Generated by Django 5.0.4 on 2024-04-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pstatus',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='', max_length=20),
        ),
    ]
