# Generated by Django 5.0.4 on 2024-05-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_alter_order_pstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='pstatus',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=20),
        ),
    ]
